In [1]:
import pandas as pd
import holidays

# 加载原始数据
data = pd.read_csv('data.csv',encoding='gbk')

# 转换日期列为日期时间类型
data['航班日期'] = pd.to_datetime(data['航班日期'])

# 提取航班日期特征
data['月份'] = data['航班日期'].dt.month
data['日期'] = data['航班日期'].dt.day
data['星期几'] = data['航班日期'].dt.dayofweek
data['季节'] = data['航班日期'].dt.quarter

# 获取节假日信息
holiday_list = holidays.China(years=data['航班日期'].dt.year.unique())

# 添加是否为节假日的列
data['节假日'] = data['航班日期'].dt.date.astype(str).map(lambda x: x in holiday_list)

# 创建新的数据集
new_data = data[['航班日期','航线金额', '月份', '日期', '星期几', '季节', '节假日']]
new_data

          航班日期        航线金额  月份  日期  星期几  季节    节假日
0   2023-01-01   168320.00   1   1    6   1   True
1   2023-01-02   222618.00   1   2    0   1   True
2   2023-01-03   304062.00   1   3    1   1  False
3   2023-01-04   377547.00   1   4    2   1  False
4   2023-01-05   297465.00   1   5    3   1  False
..         ...         ...  ..  ..  ...  ..    ...
360 2023-12-27   668665.35  12  27    2   4  False
361 2023-12-28   732326.64  12  28    3   4  False
362 2023-12-29  1040086.00  12  29    4   4  False
363 2023-12-30   740359.38  12  30    5   4  False
364 2023-12-31   503901.69  12  31    6   4  False

[365 rows x 7 columns]

In [2]:
# 可以根据需要保存新的数据集到文件
new_data.to_csv('newData.csv', index=False,encoding='gbk')